### ISSUE TITLE
Won't Install

### ISSUE THREAD

**Issue by netmancer73** [mrcomac/token-action-hud-bladerunner#1]
I've tried installing both through the installer and URL, and it says it installs, but it gives an error and the mod hasn't installed

![image](https://github.com/mrcomac/token-action-hud-bladerunner/assets/17035739/eaaac6b5-9ddc-46cf-9ee8-aa9771dec14c)

**Comment by mrcomac** [comment]
Hi there,
Are you using foundry v10?

**Comment by netmancer73** [comment]
Hi!  Yes, it says it's v10 Stable - Patch 7 (Build 303)

**Comment by mrcomac** [comment]
I didn't test it on v10. it is compatible only to v11.
