### ISSUE TITLE
Wrong version number in zipped module.json

### ISSUE THREAD

**Issue by farling42** [mrcomac/token-action-hud-bladerunner#3]
The module.json linked to release 0.0.2 has the correct 0.0.2 version

The module.json inside the zip file has 0.0.1 in it.

This means that on every "update all" it redownloads the version 0.0.2 zip, but then reports an update from 0.0.1 to 0.0.1

**Comment by farling42** [comment]
There is a github action which can be used to automate the generation of the release zip and release module.json - it removes the tedium of having to update those two files manually on every release.

**Comment by mrcomac** [comment]
fix on v0.0.3
