### ISSUE TITLE
Not compatible with latest version of Token Action HUD Core

### ISSUE THREAD

**Issue by MadBlue2112** [mrcomac/token-action-hud-bladerunner#6]
Module is only compatible with Token Action HUD Core 1.5.X, but current Token Action HUD Core version is 2.0.6

![TAHBR](https://github.com/user-attachments/assets/c2fc4f04-a6f6-4481-9dce-f3d914889240)

**Comment by r-valyar** [comment]
I second that bug report.

**Comment by mrcomac** [comment]
@r-valyar 
You probably is using the old version. Please remove it and re-install (do not update, need to remove it since the module's id has been changed)

**Comment by MadBlue2112** [comment]
That worked. Thanks!
